/* lrg-ui-event.h
 *
 * Copyright 2025 Zach Podbielniak
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * UI event representing user interaction with widgets.
 */

#pragma once

#if !defined(LIBREGNUM_INSIDE) && !defined(LIBREGNUM_COMPILATION)
#error "Only <libregnum.h> can be included directly."
#endif

#include <glib-object.h>
#include <graylib.h>
#include "../lrg-version.h"
#include "../lrg-enums.h"

G_BEGIN_DECLS

/**
 * LRG_TYPE_UI_EVENT:
 *
 * The #GType for #LrgUIEvent.
 */
#define LRG_TYPE_UI_EVENT (lrg_ui_event_get_type ())

LRG_AVAILABLE_IN_ALL
GType lrg_ui_event_get_type (void) G_GNUC_CONST;

/**
 * LrgUIEvent:
 *
 * An opaque structure representing a UI event.
 *
 * Events are generated by user input and dispatched to widgets.
 */
typedef struct _LrgUIEvent LrgUIEvent;

/* ==========================================================================
 * Construction
 * ========================================================================== */

/**
 * lrg_ui_event_new:
 * @type: the event type
 *
 * Creates a new UI event with the specified type.
 *
 * Returns: (transfer full): A new #LrgUIEvent
 */
LRG_AVAILABLE_IN_ALL
LrgUIEvent * lrg_ui_event_new (LrgUIEventType type);

/**
 * lrg_ui_event_new_mouse_move:
 * @x: the mouse X position
 * @y: the mouse Y position
 *
 * Creates a new mouse move event.
 *
 * Returns: (transfer full): A new #LrgUIEvent
 */
LRG_AVAILABLE_IN_ALL
LrgUIEvent * lrg_ui_event_new_mouse_move (gfloat x,
                                          gfloat y);

/**
 * lrg_ui_event_new_mouse_button:
 * @type: %LRG_UI_EVENT_MOUSE_BUTTON_DOWN or %LRG_UI_EVENT_MOUSE_BUTTON_UP
 * @button: the mouse button (0=left, 1=right, 2=middle)
 * @x: the mouse X position
 * @y: the mouse Y position
 *
 * Creates a new mouse button event.
 *
 * Returns: (transfer full): A new #LrgUIEvent
 */
LRG_AVAILABLE_IN_ALL
LrgUIEvent * lrg_ui_event_new_mouse_button (LrgUIEventType type,
                                            gint           button,
                                            gfloat         x,
                                            gfloat         y);

/**
 * lrg_ui_event_new_key:
 * @type: %LRG_UI_EVENT_KEY_DOWN or %LRG_UI_EVENT_KEY_UP
 * @key: the keyboard key
 *
 * Creates a new keyboard event.
 *
 * Returns: (transfer full): A new #LrgUIEvent
 */
LRG_AVAILABLE_IN_ALL
LrgUIEvent * lrg_ui_event_new_key (LrgUIEventType type,
                                   GrlKey         key);

/**
 * lrg_ui_event_new_scroll:
 * @x: the mouse X position
 * @y: the mouse Y position
 * @scroll_x: horizontal scroll amount
 * @scroll_y: vertical scroll amount
 *
 * Creates a new scroll event.
 *
 * Returns: (transfer full): A new #LrgUIEvent
 */
LRG_AVAILABLE_IN_ALL
LrgUIEvent * lrg_ui_event_new_scroll (gfloat x,
                                      gfloat y,
                                      gfloat scroll_x,
                                      gfloat scroll_y);

/**
 * lrg_ui_event_new_focus_in:
 *
 * Creates a new focus-in event.
 *
 * Returns: (transfer full): A new #LrgUIEvent
 */
LRG_AVAILABLE_IN_ALL
LrgUIEvent * lrg_ui_event_new_focus_in (void);

/**
 * lrg_ui_event_new_focus_out:
 *
 * Creates a new focus-out event.
 *
 * Returns: (transfer full): A new #LrgUIEvent
 */
LRG_AVAILABLE_IN_ALL
LrgUIEvent * lrg_ui_event_new_focus_out (void);

/* ==========================================================================
 * Copy/Free
 * ========================================================================== */

/**
 * lrg_ui_event_copy:
 * @self: an #LrgUIEvent
 *
 * Creates a copy of the UI event.
 *
 * Returns: (transfer full): A new #LrgUIEvent
 */
LRG_AVAILABLE_IN_ALL
LrgUIEvent * lrg_ui_event_copy (const LrgUIEvent *self);

/**
 * lrg_ui_event_free:
 * @self: an #LrgUIEvent
 *
 * Frees the UI event.
 */
LRG_AVAILABLE_IN_ALL
void lrg_ui_event_free (LrgUIEvent *self);

G_DEFINE_AUTOPTR_CLEANUP_FUNC (LrgUIEvent, lrg_ui_event_free)

/* ==========================================================================
 * Accessors
 * ========================================================================== */

/**
 * lrg_ui_event_get_event_type:
 * @self: an #LrgUIEvent
 *
 * Gets the type of this event.
 *
 * Returns: The event type
 */
LRG_AVAILABLE_IN_ALL
LrgUIEventType lrg_ui_event_get_event_type (const LrgUIEvent *self);

/**
 * lrg_ui_event_get_x:
 * @self: an #LrgUIEvent
 *
 * Gets the mouse X position.
 *
 * Returns: The X position
 */
LRG_AVAILABLE_IN_ALL
gfloat lrg_ui_event_get_x (const LrgUIEvent *self);

/**
 * lrg_ui_event_get_y:
 * @self: an #LrgUIEvent
 *
 * Gets the mouse Y position.
 *
 * Returns: The Y position
 */
LRG_AVAILABLE_IN_ALL
gfloat lrg_ui_event_get_y (const LrgUIEvent *self);

/**
 * lrg_ui_event_get_button:
 * @self: an #LrgUIEvent
 *
 * Gets the mouse button for mouse button events.
 *
 * Returns: The mouse button (0=left, 1=right, 2=middle)
 */
LRG_AVAILABLE_IN_ALL
gint lrg_ui_event_get_button (const LrgUIEvent *self);

/**
 * lrg_ui_event_get_key:
 * @self: an #LrgUIEvent
 *
 * Gets the keyboard key for key events.
 *
 * Returns: The key
 */
LRG_AVAILABLE_IN_ALL
GrlKey lrg_ui_event_get_key (const LrgUIEvent *self);

/**
 * lrg_ui_event_get_scroll_x:
 * @self: an #LrgUIEvent
 *
 * Gets the horizontal scroll amount.
 *
 * Returns: The horizontal scroll amount
 */
LRG_AVAILABLE_IN_ALL
gfloat lrg_ui_event_get_scroll_x (const LrgUIEvent *self);

/**
 * lrg_ui_event_get_scroll_y:
 * @self: an #LrgUIEvent
 *
 * Gets the vertical scroll amount.
 *
 * Returns: The vertical scroll amount
 */
LRG_AVAILABLE_IN_ALL
gfloat lrg_ui_event_get_scroll_y (const LrgUIEvent *self);

/* ==========================================================================
 * Event State
 * ========================================================================== */

/**
 * lrg_ui_event_get_consumed:
 * @self: an #LrgUIEvent
 *
 * Checks if the event has been consumed by a widget.
 *
 * Returns: %TRUE if consumed
 */
LRG_AVAILABLE_IN_ALL
gboolean lrg_ui_event_get_consumed (const LrgUIEvent *self);

/**
 * lrg_ui_event_set_consumed:
 * @self: an #LrgUIEvent
 * @consumed: whether the event is consumed
 *
 * Sets whether the event has been consumed.
 */
LRG_AVAILABLE_IN_ALL
void lrg_ui_event_set_consumed (LrgUIEvent *self,
                                gboolean    consumed);

/**
 * lrg_ui_event_consume:
 * @self: an #LrgUIEvent
 *
 * Marks the event as consumed.
 *
 * This is a convenience function equivalent to
 * lrg_ui_event_set_consumed(self, TRUE).
 */
LRG_AVAILABLE_IN_ALL
void lrg_ui_event_consume (LrgUIEvent *self);

G_END_DECLS
