* LrgQuestDef - Quest Definition
:PROPERTIES:
:CUSTOM_ID: lrgquestdef---quest-definition
:END:
A blueprint for a quest containing stages (objectives), rewards, and prerequisites. Quest definitions are templates that can be instantiated multiple times to track individual player progress.

** Type
:PROPERTIES:
:CUSTOM_ID: type
:END:
- *Derivable GObject Class* - Can be subclassed for custom quest behavior
- *Type ID* - =LRG_TYPE_QUEST_DEF=
- *GIR Name* - =Libregnum.QuestDef=

** Virtual Methods
:PROPERTIES:
:CUSTOM_ID: virtual-methods
:END:
*** check_prerequisites()
:PROPERTIES:
:CUSTOM_ID: check_prerequisites
:END:
#+begin_src C
gboolean (*check_prerequisites) (LrgQuestDef *self,
                                 gpointer     player);
#+end_src

Checks if quest prerequisites are met. Can be overridden for custom logic.

*** grant_rewards()
:PROPERTIES:
:CUSTOM_ID: grant_rewards
:END:
#+begin_src C
void (*grant_rewards) (LrgQuestDef *self,
                       gpointer     player);
#+end_src

Grants quest rewards to the player. Can be overridden for custom reward logic.

** Construction
:PROPERTIES:
:CUSTOM_ID: construction
:END:
*** lrg_quest_def_new()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_new
:END:
#+begin_src C
LrgQuestDef * lrg_quest_def_new (const gchar *id);
#+end_src

Creates a new quest definition.

*Parameters:*

- =id= - Unique identifier for the quest

*Returns:* A new =LrgQuestDef= (transfer full)

** Identification
:PROPERTIES:
:CUSTOM_ID: identification
:END:
*** lrg_quest_def_get_id()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_get_id
:END:
#+begin_src C
const gchar * lrg_quest_def_get_id (LrgQuestDef *self);
#+end_src

Gets the quest ID.

*Parameters:*

- =self= - An =LrgQuestDef=

*Returns:* The quest ID (transfer none)

** Quest Info
:PROPERTIES:
:CUSTOM_ID: quest-info
:END:
*** lrg_quest_def_get_name()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_get_name
:END:
#+begin_src C
const gchar * lrg_quest_def_get_name (LrgQuestDef *self);
#+end_src

Gets the quest name.

*Parameters:*

- =self= - An =LrgQuestDef=

*Returns:* The quest name (transfer none, nullable)

*** lrg_quest_def_set_name()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_set_name
:END:
#+begin_src C
void lrg_quest_def_set_name (LrgQuestDef *self,
                             const gchar *name);
#+end_src

Sets the quest name.

*Parameters:*

- =self= - An =LrgQuestDef=
- =name= - Quest name (nullable)

*** lrg_quest_def_get_description()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_get_description
:END:
#+begin_src C
const gchar * lrg_quest_def_get_description (LrgQuestDef *self);
#+end_src

Gets the quest description.

*Parameters:*

- =self= - An =LrgQuestDef=

*Returns:* The description (transfer none, nullable)

*** lrg_quest_def_set_description()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_set_description
:END:
#+begin_src C
void lrg_quest_def_set_description (LrgQuestDef *self,
                                    const gchar *description);
#+end_src

Sets the quest description.

*Parameters:*

- =self= - An =LrgQuestDef=
- =description= - Quest description (nullable)

*** lrg_quest_def_get_giver_npc()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_get_giver_npc
:END:
#+begin_src C
const gchar * lrg_quest_def_get_giver_npc (LrgQuestDef *self);
#+end_src

Gets the quest giver NPC ID.

*Parameters:*

- =self= - An =LrgQuestDef=

*Returns:* The giver NPC ID (transfer none, nullable)

*** lrg_quest_def_set_giver_npc()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_set_giver_npc
:END:
#+begin_src C
void lrg_quest_def_set_giver_npc (LrgQuestDef *self,
                                  const gchar *npc_id);
#+end_src

Sets the quest giver NPC.

*Parameters:*

- =self= - An =LrgQuestDef=
- =npc_id= - NPC ID (nullable)

** Stages/Objectives
:PROPERTIES:
:CUSTOM_ID: stagesobjectives
:END:
*** lrg_quest_def_add_stage()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_add_stage
:END:
#+begin_src C
void lrg_quest_def_add_stage (LrgQuestDef       *self,
                              LrgQuestObjective *objective);
#+end_src

Adds a stage (objective) to the quest.

*Parameters:*

- =self= - An =LrgQuestDef=
- =objective= - Objective to add as a stage (transfer full)

*** lrg_quest_def_get_stages()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_get_stages
:END:
#+begin_src C
GPtrArray * lrg_quest_def_get_stages (LrgQuestDef *self);
#+end_src

Gets all quest stages.

*Parameters:*

- =self= - An =LrgQuestDef=

*Returns:* Array of =LrgQuestObjective= (element-type, transfer none)

*** lrg_quest_def_get_stage_count()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_get_stage_count
:END:
#+begin_src C
guint lrg_quest_def_get_stage_count (LrgQuestDef *self);
#+end_src

Gets the number of stages.

*Parameters:*

- =self= - An =LrgQuestDef=

*Returns:* Stage count

*** lrg_quest_def_get_stage()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_get_stage
:END:
#+begin_src C
LrgQuestObjective * lrg_quest_def_get_stage (LrgQuestDef *self,
                                             guint        index);
#+end_src

Gets a stage by index.

*Parameters:*

- =self= - An =LrgQuestDef=
- =index= - Stage index

*Returns:* The stage objective (transfer none, nullable)

** Prerequisites
:PROPERTIES:
:CUSTOM_ID: prerequisites
:END:
*** lrg_quest_def_add_prerequisite()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_add_prerequisite
:END:
#+begin_src C
void lrg_quest_def_add_prerequisite (LrgQuestDef *self,
                                     const gchar *quest_id);
#+end_src

Adds a prerequisite quest that must be completed first.

*Parameters:*

- =self= - An =LrgQuestDef=
- =quest_id= - Prerequisite quest ID

*** lrg_quest_def_get_prerequisites()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_get_prerequisites
:END:
#+begin_src C
GPtrArray * lrg_quest_def_get_prerequisites (LrgQuestDef *self);
#+end_src

Gets all prerequisite quest IDs.

*Parameters:*

- =self= - An =LrgQuestDef=

*Returns:* Array of quest IDs (element-type utf8, transfer none)

** Rewards
:PROPERTIES:
:CUSTOM_ID: rewards
:END:
*** lrg_quest_def_set_reward_gold()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_set_reward_gold
:END:
#+begin_src C
void lrg_quest_def_set_reward_gold (LrgQuestDef *self,
                                    gint         gold);
#+end_src

Sets the gold reward.

*Parameters:*

- =self= - An =LrgQuestDef=
- =gold= - Gold reward amount

*** lrg_quest_def_get_reward_gold()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_get_reward_gold
:END:
#+begin_src C
gint lrg_quest_def_get_reward_gold (LrgQuestDef *self);
#+end_src

Gets the gold reward.

*Parameters:*

- =self= - An =LrgQuestDef=

*Returns:* Gold amount

*** lrg_quest_def_set_reward_xp()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_set_reward_xp
:END:
#+begin_src C
void lrg_quest_def_set_reward_xp (LrgQuestDef *self,
                                  gint         xp);
#+end_src

Sets the experience reward.

*Parameters:*

- =self= - An =LrgQuestDef=
- =xp= - Experience reward amount

*** lrg_quest_def_get_reward_xp()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_get_reward_xp
:END:
#+begin_src C
gint lrg_quest_def_get_reward_xp (LrgQuestDef *self);
#+end_src

Gets the experience reward.

*Parameters:*

- =self= - An =LrgQuestDef=

*Returns:* XP amount

*** lrg_quest_def_add_reward_item()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_add_reward_item
:END:
#+begin_src C
void lrg_quest_def_add_reward_item (LrgQuestDef *self,
                                    const gchar *item_id,
                                    guint        count);
#+end_src

Adds an item reward.

*Parameters:*

- =self= - An =LrgQuestDef=
- =item_id= - Item ID to reward
- =count= - Number of items

*** lrg_quest_def_get_reward_items()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_get_reward_items
:END:
#+begin_src C
GHashTable * lrg_quest_def_get_reward_items (LrgQuestDef *self);
#+end_src

Gets all item rewards as a hash table (item_id -> count).

*Parameters:*

- =self= - An =LrgQuestDef=

*Returns:* Hash table of item rewards (transfer none)

** Prerequisite Checking and Reward Granting
:PROPERTIES:
:CUSTOM_ID: prerequisite-checking-and-reward-granting
:END:
*** lrg_quest_def_check_prerequisites()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_check_prerequisites
:END:
#+begin_src C
gboolean lrg_quest_def_check_prerequisites (LrgQuestDef *self,
                                            gpointer     player);
#+end_src

Checks if all prerequisites are met.

*Parameters:*

- =self= - An =LrgQuestDef=
- =player= - (nullable) Player context

*Returns:* =TRUE= if prerequisites are satisfied

*** lrg_quest_def_grant_rewards()
:PROPERTIES:
:CUSTOM_ID: lrg_quest_def_grant_rewards
:END:
#+begin_src C
void lrg_quest_def_grant_rewards (LrgQuestDef *self,
                                  gpointer     player);
#+end_src

Grants all quest rewards.

*Parameters:*

- =self= - An =LrgQuestDef=
- =player= - (nullable) Player to grant rewards to

** Example
:PROPERTIES:
:CUSTOM_ID: example
:END:
#+begin_src C
/* Create a quest */
g_autoptr(LrgQuestDef) quest = lrg_quest_def_new("collect_herbs");
lrg_quest_def_set_name(quest, "Gather Medicinal Herbs");
lrg_quest_def_set_description(quest, "The herbalist needs rare plants");
lrg_quest_def_set_giver_npc(quest, "herbalist");

/* Add prerequisites */
lrg_quest_def_add_prerequisite(quest, "learn_herbalism");

/* Add objective: collect 5 moonflowers */
g_autoptr(LrgQuestObjective) collect = lrg_quest_objective_new(
    "collect_moonflowers",
    "Collect moonflowers",
    LRG_QUEST_OBJECTIVE_TYPE_COLLECT
);
lrg_quest_objective_set_target_id(collect, "moonflower");
lrg_quest_objective_set_target_count(collect, 5);
lrg_quest_def_add_stage(quest, collect);

/* Add rewards */
lrg_quest_def_set_reward_gold(quest, 500);
lrg_quest_def_set_reward_xp(quest, 1000);
lrg_quest_def_add_reward_item(quest, "herb_bag", 1);

/* Check prerequisites */
if (lrg_quest_def_check_prerequisites(quest, player)) {
    g_print("Can start this quest\n");
}

/* Grant rewards */
lrg_quest_def_grant_rewards(quest, player);
#+end_src
